---
- include_role:
    name: common/kubectl
    tasks_from: resource-create
  vars:
    parameters: "-f {{ sealed_secrets_download_url }}"

- include_role:
    name: common/kubectl
    tasks_from: resource-patch
  vars:
    namespace: kube-system
    type: deployment
    name: sealed-secrets-controller
    patch_parameters: ""
    patch: '{"spec":{"template":{"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"service","operator":"In","values":["system"]}]}]}}},"tolerations":[{"key":"system-app","operator":"Equal","value":"false","effect":"NoExecute"}]}}}}'

- include_role:
    name: common/kubectl
    tasks_from: rollout-status
  vars:
    name: sealed-secrets-controller
    type: deployment
    namespace: kube-system
    result_var_name: sealed_secrets_status_result

- name: encode dns admin api token
  shell: "echo -n {{ dns_admin_api_token }} | kubeseal --raw --from-file=/dev/stdin --namespace istio-system --name dns-api-key-secret"
  register: dns_admin_api_token_encoded
  changed_when: False

- include_role:
    name: common/templates
    tasks_from: process-template
  vars:
    target_dir_path: "{{ install_dir }}/sealed-secrets"
    source_file_path: roles/sealed-secrets/templates/update-secrets-template.yaml.j2
    target_file_name: update-secrets-template.yaml

- include_role:
    name: common/git
    tasks_from: pull
  vars:
    repository_url: "{{ environment_git_repo_url }}"
    private_key: "{{ environment_git_private_key }}"
    branch: "master"
    working_directory: "/tmp/environment_repository" 

- name: encode secrets
  shell: "cat {{ install_dir }}/sealed-secrets/update-secrets-template.yaml | yq w -s - /tmp/environment_repository/{{ environment_name }}/applications/values.yaml > {{ install_dir }}/sealed-secrets/values-with-secrets.yaml"
  changed_when: False
 
- name: move secrets values to git environment repository
  shell: "mv -f {{ install_dir }}/sealed-secrets/values-with-secrets.yaml /tmp/environment_repository/{{ environment_name }}/applications/values.yaml"
  changed_when: False

- include_role:
    name: common/git
    tasks_from: commit
  vars:
    message: "Generated secrets"
    working_directory: "/tmp/environment_repository" 

- include_role:
    name: common/git
    tasks_from: push
  vars:
    working_directory: "/tmp/environment_repository" 
           
