apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: System Applications
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'