apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - type: git
      url: {GIT_REPOSITORY_URL}
      name: system-apps
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: system-apps-ssh-key-secret