resource_types:
- name: terraform
  type: docker-image
  source:
    repository: totr/terraform-kube-builder
    tag: latest

resources:
- name: terraform-state
  type: terraform 
  icon: database
  source:
    env_name: ((env-name))
    backend_type: s3
    backend_config:
# see https://wasabi-support.zendesk.com/hc/en-us/articles/360003362071-How-I-do-use-Terraform-with-Wasabi-
      endpoint: "https://s3.eu-central-1.wasabisys.com"
      skip_credentials_validation: true
      skip_metadata_api_check: true
      bucket: terraform-kube
      key: terraform.tfstate
      region: eu-central-1
      access_key: ((terraform-backend-access-key))
      secret_key: ((terraform-backend-secret-key))

- name: terraform-kube
  type: git
  icon: github-circle
  source:
    uri: https://github.com/totr/terraform-kube
    branch: master
    git_crypt_key: ((git-crypt-key))

jobs:
- name: destroy-servers
  plan:
    - get: terraform-kube
    - put: terraform-state
      params:
        env_name: ((env-name))
        var_files: [terraform-kube/environments/((env-name)).tfvars]
        terraform_source: terraform-kube
        action: destroy
      get_params:
        action: destroy