resource_types:
- name: terraform
  type: docker-image
  source:
    repository: totr/terraform-kube-builder
    tag: 0.12.18

resources:
- name: terraform-state
  type: terraform 
  icon: database
  source:
    env_name: ((env-name))
    backend_type: s3
    backend_config:
# see https://wasabi-support.zendesk.com/hc/en-us/articles/360003362071-How-I-do-use-Terraform-with-Wasabi-
      endpoint: "https://s3.eu-central-1.wasabisys.com"
      skip_credentials_validation: true
      skip_metadata_api_check: true
      bucket: ((terraform-backend-bucket))
      key: terraform.tfstate
      region: eu-central-1
      access_key: ((terraform-backend-access-key))
      secret_key: ((terraform-backend-secret-key))
    env:
      ARM_PROVIDER_TWOPOINTZERO_RESOURCES: "True"

- name: terraform-kube
  type: git
  icon: github-circle
  source:
    uri: https://github.com/totr/terraform-kube
    branch: master

- name: terraform-environments
  type: git
  icon: github-circle
  source:
    uri: ((env-git-repo-uri))
    tag_filter: ((env-git-repo-tag))
    git_crypt_key: ((terraform-environments-git-crypt-key))
    private_key: ((terraform-environments-git-private-key))

jobs:
- name: destroy-servers
  plan:
    - get: terraform-kube
    - get: terraform-environments
    - put: terraform-state
      params:
        env_name: ((env-name))
        var_files: [terraform-environments/((env-name)).tfvars]
        terraform_source: terraform-kube
        action: destroy
      get_params:
        action: destroy