resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.5

resources:
- name: terraform-state
  type: terraform 
  icon: database
  source:
    env_name: ((env-name))
    backend_type: s3
    backend_config:
# see https://wasabi-support.zendesk.com/hc/en-us/articles/360003362071-How-I-do-use-Terraform-with-Wasabi-
      endpoint: "https://s3.wasabisys.com"
      skip_requesting_account_id: true
      skip_credentials_validation: true
      skip_get_ec2_platforms: true
      skip_metadata_api_check: true
      bucket: terraform-state-test
      key: terraform.tfstate
# TODO eu-central-1 not working
      region: us-east-1 
# see https://wasabi.com/wp-content/themes/wasabi/docs/Getting_Started/topics/Assigning_an_Access_Key.htm
      access_key: ((terraform-backend-access-key))
      secret_key: ((terraform-backend-secret-key))
    vars:
      tag_name: concourse
    env:
#      AWS_REGION: us-east-1
#      AWS_DEFAULT_REGION: eu-central-1

- name: terraform-kube
  type: git
  icon: github-circle
  source:
    uri: https://github.com/totr/terraform-kube
    branch: master

- name: kubespray
  type: git
  icon: github-circle
  source:
    uri: https://github.com/kubernetes-sigs/kubespray.git
    tag_filter: v2.10.4

jobs:
- name: terraform-apply
  plan:
    - get: terraform-kube
      trigger: true
    - put: terraform-state
      params:
        env_name: ((env-name))
        var_files:
        - environments/((env-name)).tfvars
        terraform_source: terraform-kube

- name: kubespray-run
  plan:
    - get: kubespray
    - get: terraform-state
      trigger: false
      passed: [terraform-apply]
      params:
        env_name: ((env-name))
        terraform_source: terraform-kube
