---
argocd_version: "1.5.8"
argocd_download_url: "https://raw.githubusercontent.com/argoproj/argo-cd/v{{ argocd_version }}/manifests/ha/install.yaml"
argocd_secret_patch: '{"stringData":{"admin.password":"{{ argocd_admin_password_encoded.stdout }}"}}'